# Generated by Django 4.1.7 on 2023-03-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(default='Subscription', max_length=255),
        ),
    ]
