# Generated by Django 4.1.7 on 2023-03-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
    ]
