# Generated by Django 4.1.7 on 2023-03-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='next_fulfillment_date',
            field=models.DateField(auto_now_add=True, default='2021-01-01'),
            preserve_default=False,
        ),
    ]
